// Auto-generated by current_performance.py — do not edit manually.
const PERF = {
  remainingTarget:    "21,491",
  salesPctAchieved:   "14.76%",
  sales:              "3,722",
  previousSalesPct:   "15.00%",
  previousSalesBags:  "2,590",
  wowSalesPct:        "+2.2%",
  wowSalesBags:       "23"
};
