"""supabase_migration.py — export the marketing dashboard's monthly data to a
SQL migration for Supabase / Postgres.

Reads monthly_report_history.json (the frozen per-month snapshots — July so far)
and writes migrations/marketing_dashboard.sql.

Run:
    python supabase_migration.py

Then in Supabase → SQL Editor → New query → paste the file → Run.
Re-runnable: each month upserts its summary row and replaces its child rows,
so running it again (or after August is added) never duplicates data.
"""
from __future__ import annotations

import json
import os

BASE = os.path.dirname(os.path.abspath(__file__))
HIST = os.path.join(BASE, "monthly_report_history.json")
OUT_DIR = os.path.join(BASE, "migrations")
OUT = os.path.join(OUT_DIR, "marketing_dashboard.sql")


def q(s) -> str:
    """SQL string literal (or NULL)."""
    if s is None:
        return "NULL"
    return "'" + str(s).replace("'", "''") + "'"


def num(x) -> str:
    """SQL numeric literal (or NULL). Ints print without a trailing .0."""
    if x is None or x == "":
        return "NULL"
    try:
        f = float(x)
        return str(int(f)) if f == int(f) else repr(f)
    except (ValueError, TypeError):
        return "NULL"


DDL = """-- ─────────────────────────────────────────────────────────────
-- Denri Africa · Marketing Dashboard — monthly data (Supabase / Postgres)
-- Generated by supabase_migration.py. Safe to re-run (idempotent per month).
-- ─────────────────────────────────────────────────────────────

create table if not exists denri_mkt_monthly (
  month_key             text primary key,
  month                 text,
  year                  int,
  generated_on          date,
  achieved_pct          numeric,
  total_sales           numeric,
  total_target          numeric,
  gap                   numeric,
  bare_minimum          numeric,
  avg_weekly            numeric,
  corporate             numeric,
  forecast              text,
  np_count              int,
  np_target             numeric,
  np_sales              numeric,
  np_deficit            numeric,
  np_kenya              numeric,
  np_outside            numeric,
  np_posts              numeric,
  combos                int,
  power_deals           int,
  kenya_combo_units     numeric,
  kenya_combo_value     numeric,
  kenya_combo_avg       numeric,
  kenya_deal_units      numeric,
  kenya_deal_value      numeric,
  kenya_deal_avg        numeric,
  sinza_units           numeric,
  sinza_value           numeric,
  sinza_cleared         numeric,
  uganda_units          numeric,
  uganda_value          numeric,
  uganda_cleared        numeric,
  posting_kenya_pct     numeric,
  posting_sinza_pct     numeric,
  posting_uganda_pct    numeric,
  posted_stock          numeric,
  unposted_stock        numeric,
  posts_made            numeric,
  notoffer_kenya        numeric,
  notoffer_sinza        numeric,
  notoffer_uganda       numeric,
  sales_from_posting    numeric,
  expected_from_posting numeric,
  comments              jsonb
);
-- Older databases created before comments existed: add it idempotently.
alter table denri_mkt_monthly add column if not exists comments jsonb;

create table if not exists denri_mkt_weekly (
  month_key      text references denri_mkt_monthly(month_key) on delete cascade,
  seq            int,
  label          text,
  week_month     text,
  pct            numeric,
  cum            numeric,
  bags           numeric,
  target_to_beat numeric,
  declined_by    numeric
);
-- Backfill the richer weekly columns on tables created before they existed.
alter table denri_mkt_weekly add column if not exists week_month     text;
alter table denri_mkt_weekly add column if not exists target_to_beat numeric;
alter table denri_mkt_weekly add column if not exists declined_by    numeric;

create table if not exists denri_mkt_new_products (
  month_key  text references denri_mkt_monthly(month_key) on delete cascade,
  name       text,
  sold       numeric,
  remaining  numeric,
  posts      numeric,
  stock      numeric
);

create table if not exists denri_mkt_offers (
  month_key  text references denri_mkt_monthly(month_key) on delete cascade,
  region     text,
  name       text,
  offer_type text,
  units      numeric,
  value      numeric,
  stock      numeric
);

-- Timed offers: one row per campaign that ran in the month, plus its bags and
-- its daily sales series (the pre-offer baseline and the offer window, which is
-- what makes the lift readable rather than just a percentage).
create table if not exists denri_mkt_timed_offers (
  month_key     text references denri_mkt_monthly(month_key) on delete cascade,
  seq           int,
  name          text,
  market        text,
  start_date    date,
  end_date      date,
  window_label  text,
  total_sold    numeric,
  total_posts   numeric,
  per_post      numeric,
  best_name     text,
  best_sold     numeric,
  total_stock   numeric,
  lift_pct      numeric,
  base_start    date,
  base_end      date,
  base_days     numeric,
  base_total    numeric,
  base_per_day  numeric,
  offer_days    numeric,
  offer_total   numeric,
  offer_per_day numeric,
  verdict       text
);

create table if not exists denri_mkt_timed_offer_bags (
  month_key    text references denri_mkt_monthly(month_key) on delete cascade,
  offer_seq    int,
  name         text,
  category     text,
  sold         numeric,
  posts        numeric,
  per_post     numeric,
  stock        numeric,
  price_was    numeric,
  price_now    numeric,
  discount_kes numeric,
  discount_pct numeric,
  bag_lift     numeric
);

create table if not exists denri_mkt_timed_offer_days (
  month_key text references denri_mkt_monthly(month_key) on delete cascade,
  offer_seq int,
  day       date,
  bags      numeric,
  in_offer  boolean
);

create table if not exists denri_mkt_timed_offer_weeks (
  month_key  text references denri_mkt_monthly(month_key) on delete cascade,
  offer_seq  int,
  seq        int,
  label      text,
  week_start date,
  week_end   date,
  total      numeric,
  days       numeric,
  per_day    numeric,
  in_offer   boolean
);

-- Self-made combos (staff CBR requests) vs running combos — one summary row per
-- month, the sold-combo lines, and the full combo-request log (CBR/2026 refs).
create table if not exists denri_mkt_self_made_summary (
  month_key       text references denri_mkt_monthly(month_key) on delete cascade,
  sm_count        numeric,
  sm_units        numeric,
  sm_value        numeric,
  run_count       numeric,
  run_units       numeric,
  run_value       numeric,
  req_total       numeric,
  req_approved    numeric,
  req_rejected    numeric,
  req_pending     numeric,
  sm_avg_colours  numeric,
  run_avg_colours numeric
);
-- Colour-range averages added after the table first shipped.
alter table denri_mkt_self_made_summary add column if not exists sm_avg_colours  numeric;
alter table denri_mkt_self_made_summary add column if not exists run_avg_colours numeric;

create table if not exists denri_mkt_combo_sales (
  month_key      text references denri_mkt_monthly(month_key) on delete cascade,
  name           text,
  self_made      boolean,
  units          numeric,
  value          numeric,
  colour_options numeric
);
-- colour_options = how many colour picks the till offers for that combo.
alter table denri_mkt_combo_sales add column if not exists colour_options numeric;

create table if not exists denri_mkt_combo_requests (
  month_key     text references denri_mkt_monthly(month_key) on delete cascade,
  cbr           text,
  combo         text,
  shop          text,
  requested_by  text,
  state         text,
  lloyd         boolean,
  price         numeric,
  requested_on  text,
  sold_units    numeric,
  reject_reason text
);
"""

# Column order for the monthly upsert.
MONTHLY_COLS = [
    "month_key", "month", "year", "generated_on", "achieved_pct", "total_sales",
    "total_target", "gap", "bare_minimum", "avg_weekly", "corporate", "forecast",
    "np_count", "np_target", "np_sales", "np_deficit", "np_kenya", "np_outside",
    "np_posts", "combos", "power_deals", "kenya_combo_units", "kenya_combo_value",
    "kenya_combo_avg", "kenya_deal_units", "kenya_deal_value", "kenya_deal_avg",
    "sinza_units", "sinza_value", "sinza_cleared", "uganda_units", "uganda_value",
    "uganda_cleared", "posting_kenya_pct", "posting_sinza_pct", "posting_uganda_pct",
    "posted_stock", "unposted_stock", "posts_made", "notoffer_kenya", "notoffer_sinza",
    "notoffer_uganda", "sales_from_posting", "expected_from_posting", "comments",
]


def month_block(key: str, s: dict) -> str:
    cp = s.get("currentPerformance", {})
    np_ = s.get("newProducts", {})
    ot = s.get("offerType", {})
    ke = ot.get("kenya", {})
    sz = ot.get("sinza", {})
    ug = ot.get("uganda", {})
    py = s.get("postingYields", {})
    noff = py.get("notOnOffer", {})

    vals = {
        "month_key": q(key), "month": q(s.get("month")), "year": num(s.get("year")),
        "generated_on": q(s.get("generatedOn")),
        "achieved_pct": num(cp.get("achievedPct")), "total_sales": num(cp.get("totalSales")),
        "total_target": num(cp.get("totalTarget")), "gap": num(cp.get("gap")),
        "bare_minimum": num(cp.get("bareMinimum")), "avg_weekly": num(cp.get("avgWeekly")),
        "corporate": num(cp.get("corporate")), "forecast": q(cp.get("forecast")),
        "np_count": num(np_.get("count")), "np_target": num(np_.get("target")),
        "np_sales": num(np_.get("sales")), "np_deficit": num(np_.get("deficit")),
        "np_kenya": num(np_.get("kenya")), "np_outside": num(np_.get("outside")),
        "np_posts": num(np_.get("posts")),
        "combos": num(ot.get("combos")), "power_deals": num(ot.get("powerDeals")),
        "kenya_combo_units": num(ke.get("comboUnits")), "kenya_combo_value": num(ke.get("comboValue")),
        "kenya_combo_avg": num(ke.get("comboAvg")), "kenya_deal_units": num(ke.get("dealUnits")),
        "kenya_deal_value": num(ke.get("dealValue")), "kenya_deal_avg": num(ke.get("dealAvg")),
        "sinza_units": num(sz.get("units")), "sinza_value": num(sz.get("value")),
        "sinza_cleared": num(sz.get("cleared")), "uganda_units": num(ug.get("units")),
        "uganda_value": num(ug.get("value")), "uganda_cleared": num(ug.get("cleared")),
        "posting_kenya_pct": num(py.get("kenyaPct")), "posting_sinza_pct": num(py.get("sinzaPct")),
        "posting_uganda_pct": num(py.get("ugandaPct")), "posted_stock": num(py.get("postedStock")),
        "unposted_stock": num(py.get("unpostedStock")), "posts_made": num(py.get("postsMade")),
        "notoffer_kenya": num(noff.get("kenya")), "notoffer_sinza": num(noff.get("sinza")),
        "notoffer_uganda": num(noff.get("uganda")), "sales_from_posting": num(py.get("salesFromPosting")),
        "expected_from_posting": num(py.get("expectedFromPosting")),
        "comments": (q(json.dumps(s.get("comments"), ensure_ascii=False)) + "::jsonb")
                    if s.get("comments") else "NULL",
    }

    out = [f"\n-- ══ {s.get('month')} {s.get('year')} ({key}) ══"]
    cols = ", ".join(MONTHLY_COLS)
    row = ", ".join(vals[c] for c in MONTHLY_COLS)
    updates = ", ".join(f"{c} = excluded.{c}" for c in MONTHLY_COLS if c != "month_key")
    out.append(
        f"insert into denri_mkt_monthly ({cols})\nvalues ({row})\n"
        f"on conflict (month_key) do update set {updates};"
    )

    # Child rows: clear this month's, then re-insert.
    out.append(f"delete from denri_mkt_weekly       where month_key = {q(key)};")
    out.append(f"delete from denri_mkt_new_products where month_key = {q(key)};")
    out.append(f"delete from denri_mkt_offers       where month_key = {q(key)};")
    out.append(f"delete from denri_mkt_timed_offer_weeks where month_key = {q(key)};")
    out.append(f"delete from denri_mkt_timed_offer_days  where month_key = {q(key)};")
    out.append(f"delete from denri_mkt_timed_offer_bags  where month_key = {q(key)};")
    out.append(f"delete from denri_mkt_timed_offers      where month_key = {q(key)};")
    out.append(f"delete from denri_mkt_self_made_summary where month_key = {q(key)};")
    out.append(f"delete from denri_mkt_combo_sales       where month_key = {q(key)};")
    out.append(f"delete from denri_mkt_combo_requests    where month_key = {q(key)};")

    for i, w in enumerate(cp.get("weekly", []), start=1):
        out.append(
            "insert into denri_mkt_weekly (month_key, seq, label, week_month, pct, cum, bags, "
            "target_to_beat, declined_by) values ("
            f"{q(key)}, {i}, {q(w.get('label'))}, {q(w.get('month'))}, {num(w.get('pct'))}, "
            f"{num(w.get('cum'))}, {num(w.get('bags'))}, {num(w.get('targetToBeat'))}, "
            f"{num(w.get('declinedBy'))});"
        )
    for p in np_.get("products", []):
        out.append(
            "insert into denri_mkt_new_products (month_key, name, sold, remaining, posts, stock) values ("
            f"{q(key)}, {q(p.get('name'))}, {num(p.get('sold'))}, {num(p.get('remaining'))}, "
            f"{num(p.get('posts'))}, {num(p.get('stock'))});"
        )
    # Kenya per-offer (falls back to the two aggregates if no per-offer list),
    # then Sinza & Uganda per-offer.
    offer_rows = []
    ke_offers = ke.get("offers", [])
    if ke_offers:
        for o in ke_offers:
            offer_rows.append(("Kenya", o.get("name"), o.get("type"), o.get("units"), None, None))
    else:
        offer_rows.append(("Kenya", "Combos", "combo", ke.get("comboUnits"), ke.get("comboValue"), None))
        offer_rows.append(("Kenya", "Power Deals", "deal", ke.get("dealUnits"), ke.get("dealValue"), None))
    for o in sz.get("offers", []):
        offer_rows.append(("Sinza", o.get("name"), o.get("type"), o.get("units"), None, o.get("stock")))
    for o in ug.get("offers", []):
        offer_rows.append(("Uganda", o.get("name"), o.get("type"), o.get("units"), None, o.get("stock")))
    for region, name, otype, units, value, stock in offer_rows:
        out.append(
            "insert into denri_mkt_offers (month_key, region, name, offer_type, units, value, stock) values ("
            f"{q(key)}, {q(region)}, {q(name)}, {q(otype)}, {num(units)}, {num(value)}, {num(stock)});"
        )

    # Timed offers — campaign row, then its bags and its daily series, keyed by
    # the campaign's position in the month so the three tables join up.
    for i, c in enumerate(s.get("timedOffers", []), start=1):
        out.append(
            "insert into denri_mkt_timed_offers (month_key, seq, name, market, start_date, end_date, "
            "window_label, total_sold, total_posts, per_post, best_name, best_sold, total_stock, "
            "lift_pct, base_start, base_end, base_days, base_total, base_per_day, offer_days, "
            "offer_total, offer_per_day, verdict) values ("
            f"{q(key)}, {i}, {q(c.get('name'))}, {q(c.get('market'))}, {q(c.get('startDate'))}, "
            f"{q(c.get('endDate'))}, {q(c.get('windowLabel'))}, {num(c.get('totalSold'))}, "
            f"{num(c.get('totalPosts'))}, {num(c.get('perPost'))}, {q(c.get('bestName'))}, "
            f"{num(c.get('bestSold'))}, {num(c.get('totalStock'))}, {num(c.get('liftPct'))}, "
            f"{q(c.get('baseStart'))}, {q(c.get('baseEnd'))}, {num(c.get('baseDays'))}, "
            f"{num(c.get('baseTotal'))}, {num(c.get('basePerDay'))}, {num(c.get('offerDays'))}, "
            f"{num(c.get('offerTotal'))}, {num(c.get('offerPerDay'))}, {q(c.get('verdict'))});"
        )
        for b in c.get("bags", []):
            out.append(
                "insert into denri_mkt_timed_offer_bags (month_key, offer_seq, name, category, sold, "
                "posts, per_post, stock, price_was, price_now, discount_kes, discount_pct, bag_lift) values ("
                f"{q(key)}, {i}, {q(b.get('name'))}, {q(b.get('category'))}, {num(b.get('sold'))}, "
                f"{num(b.get('posts'))}, {num(b.get('perPost'))}, {num(b.get('stock'))}, "
                f"{num(b.get('priceWas'))}, {num(b.get('priceNow'))}, {num(b.get('discountKes'))}, "
                f"{num(b.get('discountPct'))}, {num(b.get('bagLift'))});"
            )
        for day in c.get("daily", []):
            out.append(
                "insert into denri_mkt_timed_offer_days (month_key, offer_seq, day, bags, in_offer) values ("
                f"{q(key)}, {i}, {q(day.get('date'))}, {num(day.get('bags'))}, "
                f"{'true' if day.get('off') else 'false'});"
            )
        for j, wk in enumerate(c.get("weekly", []), start=1):
            out.append(
                "insert into denri_mkt_timed_offer_weeks (month_key, offer_seq, seq, label, "
                "week_start, week_end, total, days, per_day, in_offer) values ("
                f"{q(key)}, {i}, {j}, {q(wk.get('label'))}, {q(wk.get('start'))}, {q(wk.get('end'))}, "
                f"{num(wk.get('total'))}, {num(wk.get('days'))}, {num(wk.get('perDay'))}, "
                f"{'true' if wk.get('off') else 'false'});"
            )

    # Self-made combos — summary row, the sold-combo lines, and the CBR request log.
    smc = s.get("selfMadeCombos")
    if smc:
        sm = smc.get("smTotals", {})
        run = smc.get("runTotals", {})
        rc = smc.get("reqCounts", {})
        out.append(
            "insert into denri_mkt_self_made_summary (month_key, sm_count, sm_units, sm_value, "
            "run_count, run_units, run_value, req_total, req_approved, req_rejected, req_pending, "
            "sm_avg_colours, run_avg_colours) values ("
            f"{q(key)}, {num(sm.get('count'))}, {num(sm.get('units'))}, {num(sm.get('value'))}, "
            f"{num(run.get('count'))}, {num(run.get('units'))}, {num(run.get('value'))}, "
            f"{num(smc.get('reqTotal'))}, {num(rc.get('approved'))}, {num(rc.get('rejected'))}, "
            f"{num(rc.get('pending'))}, {num(sm.get('avgColours'))}, {num(run.get('avgColours'))});"
        )
        for o in smc.get("selfMade", []):
            out.append(
                "insert into denri_mkt_combo_sales (month_key, name, self_made, units, value, colour_options) values ("
                f"{q(key)}, {q(o.get('name'))}, true, {num(o.get('qty'))}, {num(o.get('value'))}, "
                f"{num(o.get('colourOptions'))});"
            )
        for o in smc.get("running", []):
            out.append(
                "insert into denri_mkt_combo_sales (month_key, name, self_made, units, value, colour_options) values ("
                f"{q(key)}, {q(o.get('name'))}, false, {num(o.get('qty'))}, {num(o.get('value'))}, "
                f"{num(o.get('colourOptions'))});"
            )
        for r in smc.get("requests", []):
            out.append(
                "insert into denri_mkt_combo_requests (month_key, cbr, combo, shop, requested_by, "
                "state, lloyd, price, requested_on, sold_units, reject_reason) values ("
                f"{q(key)}, {q(r.get('cbr'))}, {q(r.get('combo'))}, {q(r.get('shop'))}, "
                f"{q(r.get('by'))}, {q(r.get('state'))}, {'true' if r.get('lloyd') else 'false'}, "
                f"{num(r.get('price'))}, {q(r.get('on'))}, {num(r.get('soldUnits'))}, "
                f"{q(r.get('reject'))});"
            )
    return "\n".join(out)


def main() -> None:
    hist = json.load(open(HIST, encoding="utf-8"))
    parts = [DDL]
    for key in sorted(hist):
        parts.append(month_block(key, hist[key]))
    parts.append("")

    os.makedirs(OUT_DIR, exist_ok=True)
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(parts))

    months = ", ".join(sorted(hist))
    print(f"Wrote {os.path.relpath(OUT, BASE)} — {len(hist)} month(s): {months}")
    print("Open Supabase → SQL Editor → New query → paste it → Run.")


if __name__ == "__main__":
    main()
