"""supabase_migration.py — export the marketing dashboard's monthly data to a
SQL migration for Supabase / Postgres.

Reads monthly_report_history.json (the frozen per-month snapshots — July so far)
and writes migrations/marketing_dashboard.sql.

Run:
    python supabase_migration.py

Then in Supabase → SQL Editor → New query → paste the file → Run.
Re-runnable: each month upserts its summary row and replaces its child rows,
so running it again (or after August is added) never duplicates data.
"""
from __future__ import annotations

import json
import os

BASE = os.path.dirname(os.path.abspath(__file__))
HIST = os.path.join(BASE, "monthly_report_history.json")
OUT_DIR = os.path.join(BASE, "migrations")
OUT = os.path.join(OUT_DIR, "marketing_dashboard.sql")


def q(s) -> str:
    """SQL string literal (or NULL)."""
    if s is None:
        return "NULL"
    return "'" + str(s).replace("'", "''") + "'"


def num(x) -> str:
    """SQL numeric literal (or NULL). Ints print without a trailing .0."""
    if x is None or x == "":
        return "NULL"
    try:
        f = float(x)
        return str(int(f)) if f == int(f) else repr(f)
    except (ValueError, TypeError):
        return "NULL"


DDL = """-- ─────────────────────────────────────────────────────────────
-- Denri Africa · Marketing Dashboard — monthly data (Supabase / Postgres)
-- Generated by supabase_migration.py. Safe to re-run (idempotent per month).
-- ─────────────────────────────────────────────────────────────

create table if not exists denri_mkt_monthly (
  month_key             text primary key,
  month                 text,
  year                  int,
  generated_on          date,
  achieved_pct          numeric,
  total_sales           numeric,
  total_target          numeric,
  gap                   numeric,
  bare_minimum          numeric,
  avg_weekly            numeric,
  corporate             numeric,
  forecast              text,
  np_count              int,
  np_target             numeric,
  np_sales              numeric,
  np_deficit            numeric,
  np_kenya              numeric,
  np_outside            numeric,
  np_posts              numeric,
  combos                int,
  power_deals           int,
  kenya_combo_units     numeric,
  kenya_combo_value     numeric,
  kenya_combo_avg       numeric,
  kenya_deal_units      numeric,
  kenya_deal_value      numeric,
  kenya_deal_avg        numeric,
  sinza_units           numeric,
  sinza_value           numeric,
  sinza_cleared         numeric,
  uganda_units          numeric,
  uganda_value          numeric,
  uganda_cleared        numeric,
  posting_kenya_pct     numeric,
  posting_sinza_pct     numeric,
  posting_uganda_pct    numeric,
  posted_stock          numeric,
  unposted_stock        numeric,
  posts_made            numeric,
  notoffer_kenya        numeric,
  notoffer_sinza        numeric,
  notoffer_uganda       numeric,
  sales_from_posting    numeric,
  expected_from_posting numeric
);

create table if not exists denri_mkt_weekly (
  month_key  text references denri_mkt_monthly(month_key) on delete cascade,
  seq        int,
  label      text,
  pct        numeric,
  cum        numeric,
  bags       numeric
);

create table if not exists denri_mkt_new_products (
  month_key  text references denri_mkt_monthly(month_key) on delete cascade,
  name       text,
  sold       numeric,
  remaining  numeric,
  posts      numeric,
  stock      numeric
);

create table if not exists denri_mkt_offers (
  month_key  text references denri_mkt_monthly(month_key) on delete cascade,
  region     text,
  name       text,
  offer_type text,
  units      numeric,
  value      numeric,
  stock      numeric
);
"""

# Column order for the monthly upsert.
MONTHLY_COLS = [
    "month_key", "month", "year", "generated_on", "achieved_pct", "total_sales",
    "total_target", "gap", "bare_minimum", "avg_weekly", "corporate", "forecast",
    "np_count", "np_target", "np_sales", "np_deficit", "np_kenya", "np_outside",
    "np_posts", "combos", "power_deals", "kenya_combo_units", "kenya_combo_value",
    "kenya_combo_avg", "kenya_deal_units", "kenya_deal_value", "kenya_deal_avg",
    "sinza_units", "sinza_value", "sinza_cleared", "uganda_units", "uganda_value",
    "uganda_cleared", "posting_kenya_pct", "posting_sinza_pct", "posting_uganda_pct",
    "posted_stock", "unposted_stock", "posts_made", "notoffer_kenya", "notoffer_sinza",
    "notoffer_uganda", "sales_from_posting", "expected_from_posting",
]


def month_block(key: str, s: dict) -> str:
    cp = s.get("currentPerformance", {})
    np_ = s.get("newProducts", {})
    ot = s.get("offerType", {})
    ke = ot.get("kenya", {})
    sz = ot.get("sinza", {})
    ug = ot.get("uganda", {})
    py = s.get("postingYields", {})
    noff = py.get("notOnOffer", {})

    vals = {
        "month_key": q(key), "month": q(s.get("month")), "year": num(s.get("year")),
        "generated_on": q(s.get("generatedOn")),
        "achieved_pct": num(cp.get("achievedPct")), "total_sales": num(cp.get("totalSales")),
        "total_target": num(cp.get("totalTarget")), "gap": num(cp.get("gap")),
        "bare_minimum": num(cp.get("bareMinimum")), "avg_weekly": num(cp.get("avgWeekly")),
        "corporate": num(cp.get("corporate")), "forecast": q(cp.get("forecast")),
        "np_count": num(np_.get("count")), "np_target": num(np_.get("target")),
        "np_sales": num(np_.get("sales")), "np_deficit": num(np_.get("deficit")),
        "np_kenya": num(np_.get("kenya")), "np_outside": num(np_.get("outside")),
        "np_posts": num(np_.get("posts")),
        "combos": num(ot.get("combos")), "power_deals": num(ot.get("powerDeals")),
        "kenya_combo_units": num(ke.get("comboUnits")), "kenya_combo_value": num(ke.get("comboValue")),
        "kenya_combo_avg": num(ke.get("comboAvg")), "kenya_deal_units": num(ke.get("dealUnits")),
        "kenya_deal_value": num(ke.get("dealValue")), "kenya_deal_avg": num(ke.get("dealAvg")),
        "sinza_units": num(sz.get("units")), "sinza_value": num(sz.get("value")),
        "sinza_cleared": num(sz.get("cleared")), "uganda_units": num(ug.get("units")),
        "uganda_value": num(ug.get("value")), "uganda_cleared": num(ug.get("cleared")),
        "posting_kenya_pct": num(py.get("kenyaPct")), "posting_sinza_pct": num(py.get("sinzaPct")),
        "posting_uganda_pct": num(py.get("ugandaPct")), "posted_stock": num(py.get("postedStock")),
        "unposted_stock": num(py.get("unpostedStock")), "posts_made": num(py.get("postsMade")),
        "notoffer_kenya": num(noff.get("kenya")), "notoffer_sinza": num(noff.get("sinza")),
        "notoffer_uganda": num(noff.get("uganda")), "sales_from_posting": num(py.get("salesFromPosting")),
        "expected_from_posting": num(py.get("expectedFromPosting")),
    }

    out = [f"\n-- ══ {s.get('month')} {s.get('year')} ({key}) ══"]
    cols = ", ".join(MONTHLY_COLS)
    row = ", ".join(vals[c] for c in MONTHLY_COLS)
    updates = ", ".join(f"{c} = excluded.{c}" for c in MONTHLY_COLS if c != "month_key")
    out.append(
        f"insert into denri_mkt_monthly ({cols})\nvalues ({row})\n"
        f"on conflict (month_key) do update set {updates};"
    )

    # Child rows: clear this month's, then re-insert.
    out.append(f"delete from denri_mkt_weekly       where month_key = {q(key)};")
    out.append(f"delete from denri_mkt_new_products where month_key = {q(key)};")
    out.append(f"delete from denri_mkt_offers       where month_key = {q(key)};")

    for i, w in enumerate(cp.get("weekly", []), start=1):
        out.append(
            "insert into denri_mkt_weekly (month_key, seq, label, pct, cum, bags) values ("
            f"{q(key)}, {i}, {q(w.get('label'))}, {num(w.get('pct'))}, {num(w.get('cum'))}, {num(w.get('bags'))});"
        )
    for p in np_.get("products", []):
        out.append(
            "insert into denri_mkt_new_products (month_key, name, sold, remaining, posts, stock) values ("
            f"{q(key)}, {q(p.get('name'))}, {num(p.get('sold'))}, {num(p.get('remaining'))}, "
            f"{num(p.get('posts'))}, {num(p.get('stock'))});"
        )
    # Kenya combos/power deals as two aggregate offer rows, then Sinza & Uganda per-offer.
    offer_rows = [
        ("Kenya", "Combos", "combo", ke.get("comboUnits"), ke.get("comboValue"), None),
        ("Kenya", "Power Deals", "deal", ke.get("dealUnits"), ke.get("dealValue"), None),
    ]
    for o in sz.get("offers", []):
        offer_rows.append(("Sinza", o.get("name"), o.get("type"), o.get("units"), None, o.get("stock")))
    for o in ug.get("offers", []):
        offer_rows.append(("Uganda", o.get("name"), o.get("type"), o.get("units"), None, o.get("stock")))
    for region, name, otype, units, value, stock in offer_rows:
        out.append(
            "insert into denri_mkt_offers (month_key, region, name, offer_type, units, value, stock) values ("
            f"{q(key)}, {q(region)}, {q(name)}, {q(otype)}, {num(units)}, {num(value)}, {num(stock)});"
        )
    return "\n".join(out)


def main() -> None:
    hist = json.load(open(HIST, encoding="utf-8"))
    parts = [DDL]
    for key in sorted(hist):
        parts.append(month_block(key, hist[key]))
    parts.append("")

    os.makedirs(OUT_DIR, exist_ok=True)
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(parts))

    months = ", ".join(sorted(hist))
    print(f"Wrote {os.path.relpath(OUT, BASE)} — {len(hist)} month(s): {months}")
    print("Open Supabase → SQL Editor → New query → paste it → Run.")


if __name__ == "__main__":
    main()
